<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 2</b></center>    
<pre>



### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. See the first 25 entries

In [ ]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [8]:
df.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [10]:
# df.shape[0]
len(df)

943

### Step 7. What is the number of columns in the dataset?

In [13]:
df.shape[1]

5

### Step 8. Print the name of all the columns.

In [ ]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='str')

### Step 9. How is the dataset indexed?

In [15]:
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [17]:
df.dtypes

user_id       int64
age           int64
gender          str
occupation      str
zip_code        str
dtype: object

### Step 11. Print only the occupation column

In [19]:
df["occupation"]

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

### Step 12. How many different occupations are in this dataset?

In [22]:
df['occupation'].unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

### Step 13. What is the most frequent occupation?

In [28]:
df['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [30]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [31]:
df.describe(include='all')

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [33]:
df['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [34]:
df['age'].mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [35]:
df['age'].value_counts().idxmin()

np.int64(7)

## Part -2

- **All tasks** are based on the **single dataset** loaded in the Setup cell below.

In [5]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

cities    = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'Dallas', 'Austin', 'Seattle']
regions   = {'New York': 'East', 'Los Angeles': 'West', 'Chicago': 'North',
             'Houston': 'South', 'Phoenix': 'West', 'Philadelphia': 'East',
             'San Antonio': 'South', 'Dallas': 'South', 'Austin': 'South', 'Seattle': 'West'}
categories = ['Electronics', 'Clothing', 'Food', 'Furniture']
products   = {
    'Electronics': ['Laptop', 'Smartphone', 'Headphones', 'Tablet', 'Camera'],
    'Clothing':    ['T-Shirt', 'Jeans', 'Jacket', 'Sneakers', 'Dress'],
    'Food':        ['Coffee Beans', 'Olive Oil', 'Pasta', 'Chocolate', 'Tea'],
    'Furniture':   ['Office Chair', 'Desk', 'Bookshelf', 'Sofa', 'Lamp']
}
prices     = {
    'Laptop': 999.99, 'Smartphone': 799.99, 'Headphones': 199.99,
    'Tablet': 499.99, 'Camera': 649.99, 'T-Shirt': 29.99,
    'Jeans': 59.99, 'Jacket': 89.99, 'Sneakers': 79.99, 'Dress': 69.99,
    'Coffee Beans': 14.99, 'Olive Oil': 12.99, 'Pasta': 5.99,
    'Chocolate': 8.99, 'Tea': 9.99, 'Office Chair': 249.99,
    'Desk': 349.99, 'Bookshelf': 149.99, 'Sofa': 799.99, 'Lamp': 49.99
}
salespersons = ['Alice Johnson', 'Bob Martinez', 'Carol White',
                'David Lee', 'Emma Davis']
first_names  = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer',
                'Michael', 'Linda', 'William', 'Barbara', 'David', 'Susan',
                'Richard', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
                'Daniel', 'Lisa']
last_names   = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia',
                'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson',
                'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
                'Young', 'Robinson']

city_list    = np.random.choice(cities, n)
cat_list     = np.random.choice(categories, n)
prod_list    = [np.random.choice(products[c]) for c in cat_list]
price_list   = np.array([prices[p] for p in prod_list])
disc_list    = np.random.choice([0, 5, 10, 15, 20, 25, 30], n)
qty_list     = np.random.randint(1, 11, n)
rating_list  = np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.10, 0.20, 0.40, 0.25])
dates        = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n)
dates        = pd.to_datetime(np.sort(np.random.choice(dates, n, replace=False)))
cust_names   = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(n)]

# Introduce some missing values
rating_arr = rating_list.astype(float)
rating_arr[np.random.choice(n, 12, replace=False)] = np.nan
disc_arr = disc_list.astype(float)
disc_arr[np.random.choice(n, 8, replace=False)] = np.nan

df = pd.DataFrame({
    'order_id':      [f'ORD-{1000+i}' for i in range(n)],
    'order_date':    dates,
    'customer_name': cust_names,
    'city':          city_list,
    'region':        [regions[c] for c in city_list],
    'category':      cat_list,
    'product':       prod_list,
    'quantity':      qty_list,
    'unit_price':    price_list,
    'discount':      disc_arr,
    'salesperson':   np.random.choice(salespersons, n),
    'rating':        rating_arr
})

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[[5, 23, 77]]], ignore_index=True)


df.head()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0

### ✅ Task 1 — First Inspection
Perform a basic inspection of the DataFrame `df`:
1. Display the **first 8 rows**.
2. Display the **last 5 rows**.
3. Print the **shape** (rows, columns).
4. Print all **column names**.

In [ ]:
# df.head(8)
# df.tail(5)
# df.shape
# df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region', 'category',
       'product', 'quantity', 'unit_price', 'discount', 'salesperson',
       'rating'],
      dtype='str')

### ✅ Task 2 — Data Types & Info
1. Display the **data type** of each column using `.dtypes`.
2. Use `.info()` to get a full summary.
3. Identify which columns have **missing values** and how many.

In [ ]:
# df.dtypes
# df.info()
# df.isnull().sum()

order_id          0
order_date        0
customer_name     0
city              0
region            0
category          0
product           0
quantity          0
unit_price        0
discount          8
salesperson       0
rating           13
dtype: int64

### ✅ Task 3 — Descriptive Statistics
1. Use `.describe()` to get summary statistics for **all numeric columns**.
2. Use `.describe(include='object')` to get statistics for **text columns**.
3. Print the **mean**, **min**, and **max** of `unit_price` separately.

In [50]:
# df.describe()
# df.describe(include='object')
# df['unit_price'].mean()
# df['unit_price'].min()
df['unit_price'].max()

np.float64(999.99)

### ✅ Task 4 — Selecting Columns
1. Select and display only the `customer_name` and `city` columns.
2. Select the columns `product`, `quantity`, `unit_price` and display the **first 10 rows**.
3. Store the `unit_price` column as a **Pandas Series** named `prices_series` and print its type.

In [59]:
# df[['customer_name', 'city']]
# df[['customer_name', 'city', 'unit_price']]
price_series = df['unit_price']
type(price_series)

pandas.Series

### ✅ Task 5 — Filtering Rows
Filter and display:
1. All orders from the **'Electronics'** category.
2. All orders where `quantity` is **greater than 7**.
3. All orders from **'New York'** city.
4. Print the **row count** for each filtered result.

In [69]:
# df[df['category'] == 'Electronics']
# df[df['quantity'] > 7]
# df[df['city'] == 'New York']

# df[df['category'] == 'Electronics'].shape[0]
# df[df['quantity'] > 7].shape[0]
df[df['city'] == 'New York'].shape[0]

23

### ✅ Task 6 — Sorting
1. Sort the DataFrame by `unit_price` in **descending order** and display the top 10 rows.
2. Sort by `category` (ascending) and then by `unit_price` (descending) — **multi-column sort**.
3. Display the **cheapest 5 products** (by unit_price).

In [73]:
# df.sort_values(by='unit_price', ascending=False).head(10)
# df.sort_values(by=['category', 'unit_price'], ascending=[True, False])
df.sort_values(by='unit_price', ascending=False).tail(5)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
85,ORD-1085,2023-06-05 11:27:26.231155,Barbara Moore,Dallas,South,Food,Chocolate,8,8.99,0.0,Carol White,4.0
123,ORD-1123,2023-08-13 23:38:17.487437,Susan White,San Antonio,South,Food,Pasta,8,5.99,30.0,Alice Johnson,2.0
114,ORD-1114,2023-07-28 12:32:33.768844,Jessica Johnson,New York,East,Food,Pasta,8,5.99,10.0,Bob Martinez,4.0
140,ORD-1140,2023-09-14 01:55:46.733668,Thomas Jackson,Seattle,West,Food,Pasta,9,5.99,15.0,David Lee,5.0
196,ORD-1196,2023-12-25 12:18:05.427135,Michael Anderson,Phoenix,West,Food,Pasta,2,5.99,0.0,Alice Johnson,5.0

### ✅ Task 7 — Value Counts
1. Count how many orders belong to each **category**.
2. Count how many orders were handled by each **salesperson**.
3. Find the **most common city** in the dataset.
4. Show the distribution of **customer ratings** (including NaN count).

In [6]:
# df['category'].value_counts()
# df['salesperson'].value_counts()
# df['city'].mode()
df['rating'].isna().sum()

np.int64(13)

### ✅ Task 8 — Adding a New Column
Add a new column called **`total_revenue`** computed as:
> `total_revenue = quantity × unit_price × (1 - discount / 100)`

> ⚠️ Treat missing `discount` values as **0** (no discount).

Print the first 10 rows showing `product`, `quantity`, `unit_price`, `discount`, and `total_revenue`.

In [14]:
# df['total_revenue'] = (df['quantity']*df['unit_price']*(1 - df['discount'].fillna(0) / 100))
df[['product', 'quantity', 'unit_price', 'discount', 'total_revenue']].head(10)

        product  quantity  unit_price  discount  total_revenue
0        Jacket         1       89.99      10.0        80.9910
1     Olive Oil         5       12.99      15.0        55.2075
2     Olive Oil         7       12.99       0.0        90.9300
3          Desk         6      349.99      15.0      1784.9490
4  Office Chair         1      249.99      10.0       224.9910
5        Laptop         5      999.99      20.0      3999.9600
6        Laptop         5      999.99      15.0      4249.9575
7     Bookshelf         6      149.99      20.0       719.9520
8           Tea         3        9.99      30.0        20.9790
9         Jeans         5       59.99       0.0       299.9500

### ✅ Task 9 — Handling Missing Values
1. Count the total number of missing values in the **entire DataFrame**.
2. Fill missing `rating` values with the **median** rating.
3. Fill missing `discount` values with **0**.
4. Confirm there are **no more missing values** after filling.

In [12]:
# df.isna().sum().sum()
# df['rating'] = df['rating'].fillna(df['rating'].median())
# df['discount'] = df['discount'].fillna(0)
df.isna().sum().sum()

np.int64(0)

### ✅ Task 10 — Removing Duplicates
1. Check how many **duplicate rows** exist in the DataFrame.
2. Display the duplicate rows.
3. Remove duplicates and store the clean DataFrame back into `df`.
4. Confirm the new shape.

In [ ]:
# df.duplicated().sum()
# df[df.duplicated()]
df.drop_duplicates()
df.shape()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
200,ORD-1005,2023-01-10 03:29:50.954773,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
201,ORD-1023,2023-02-12 01:41:18.391959,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,NaN
202,ORD-1077,2023-05-21 20:15:40.703517,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0

### ✅ Task 11 — Renaming and Dropping Columns
1. Rename the column `unit_price` to `price_usd` and `customer_name` to `customer`.
2. Drop the column `order_id` from a **copy** of the DataFrame (do not modify `df`).
3. Reset the index of that copy and print it.

In [ ]:
# df = df.rename(columns={'unit_price': 'price_usd', 'customer_name': 'customer'})
# df_copy = df.drop(columns=['order_id']).copy()
# df_copy = df_copy.reset_index(drop=True)

### ✅ Task 12 — `loc` and `iloc`
Using the original `df`:
1. Use **`iloc`** to select rows 10 to 20 and the first 4 columns.
2. Use **`loc`** to select all rows where `region == 'West'`, showing only `city`, `product`, and `unit_price`.
3. Use **`loc`** to update the `discount` of row at index `0` to `50`.

In [25]:
# df.iloc[10:21, 0:4]
# df.loc[df['region'] == 'West', ['city', 'product', 'price_usd']]
df.loc[0, 'discount'] = 50